# Generated by Django 5.1.3 on 2024-12-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='customer_id',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
