# Generated by Django 5.1.3 on 2024-12-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accesstoken_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
