services:
  mysql:
    container_name: trades_db
    image: mysql:8.0
    volumes:
      - tradesdb:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-h",
          "localhost",
          "-u",
          "root",
          "-ppassword",
          "-e",
          "SELECT 1",
        ]
      timeout: 5s
      retries: 10

  redis:
    container_name: trades_redis
    image: redis:7.4.2
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 10

  backend:
    container_name: trades_backend
    build:
      context: backend/
    command: >
      bash -c "python manage.py makemigrations &&
                python manage.py migrate &&
                python manage.py createsuperuser --username=admin --email=admin@example.com --noinput
                gunicorn TradeScheduler.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql
      - CELERY_BROKER=redis://redis:6379/0
      - DJANGO_SUPERUSER_PASSWORD=admin
    depends_on:
      mysql:
        condition: service_healthy

  celery:
    container_name: trades_celery
    build:
      context: backend/
    command: celery -A TradeScheduler worker -l INFO
    env_file:
      - .env
    environment:
      - DB_HOST=mysql
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  tradesdb:
  redisdata:
