# Generated by Django 5.1.3 on 2024-12-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtrade',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='scheduledtrade',
            name='units',
            field=models.IntegerField(),
        ),
    ]
