# Generated by Django 5.1.3 on 2024-12-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_alter_scheduledtrade_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtrade',
            name='hood_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
