# Generated by Django 5.1.4 on 2024-12-10 20:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(choices=[('EUR_USD', 'EURUSD'), ('AUD_USD', 'AUDUSD'), ('USD_JPY', 'USDJPY'), ('USD_CAD', 'USDCAD'), ('NZD_USD', 'NZDUSD'), ('AUD_JPY', 'AUDJPY'), ('USD_CHF', 'USDCHF')], max_length=20)),
                ('units', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-9')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('take_profit', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.09'))])),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.09'))])),
                ('scheduled_time', models.DateTimeField()),
                ('action', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=4)),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
