# Generated by Django 5.1.4 on 2024-12-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_alter_scheduledtrade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtrade',
            name='posthook_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
