# Generated by Django 5.1.4 on 2025-02-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_scheduledtrade_posthook_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledtrade',
            old_name='posthook_id',
            new_name='task_id',
        ),
    ]
